In [9]:
import numpy as np

In [21]:
N_a = np.array([[1, 2, 3, 4]], dtype=float).T
N_a

array([[1.],
       [2.],
       [3.],
       [4.]])

In [22]:
'''M_a = np.array([
 [1, 0.5, 0, 0],
 [0.5, 1, 0, 0],
 [0, 0, 1, 0.5],
 [0, 0, 0.5, 1]
], dtype=float)
M_a'''

M_a = np.array([
 [1,  0, 0, 0],
 [0.5, 1, 0, 0],
 [0, 0, 1,  0],
 [0, 0, 0, 1]
], dtype=float)
M_a

array([[1. , 0. , 0. , 0. ],
       [0.5, 1. , 0. , 0. ],
       [0. , 0. , 1. , 0. ],
       [0. , 0. , 0. , 1. ]])

In [25]:
g_ba = np.array([
 [1, 1, 1, 1],
], dtype=float)
g_ba

array([[1., 1., 1., 1.]])

In [26]:
# Moore-Penrose pseudo-inverse
g_ba_pinv = np.linalg.pinv(g_ba)
g_ba_pinv

array([[0.25],
       [0.25],
       [0.25],
       [0.25]])

In [27]:
N_b = g_ba @ N_a
N_b

array([[10.]])

In [36]:
g_ba @ M_a

array([[1.5, 1. , 1. , 1. ]])

In [28]:
g_ba @ g_ba_pinv

array([[1.]])

In [29]:
g_ba_pinv @ g_ba

array([[0.25, 0.25, 0.25, 0.25],
       [0.25, 0.25, 0.25, 0.25],
       [0.25, 0.25, 0.25, 0.25],
       [0.25, 0.25, 0.25, 0.25]])

In [30]:
N_a = g_ba_pinv @ N_b
N_a

array([[2.5],
       [2.5],
       [2.5],
       [2.5]])

In [34]:
np.linalg.eig(M_a)

(array([1., 1., 1., 1.]),
 array([[ 0.0000000e+00,  4.4408921e-16,  0.0000000e+00,  0.0000000e+00],
        [ 1.0000000e+00, -1.0000000e+00,  0.0000000e+00,  0.0000000e+00],
        [ 0.0000000e+00,  0.0000000e+00,  1.0000000e+00,  0.0000000e+00],
        [ 0.0000000e+00,  0.0000000e+00,  0.0000000e+00,  1.0000000e+00]]))

In [31]:
g_ba_pinv_2 = np.array([
    [1./3, 0],
    [2./3, 0],
    [0,    1./4],
    [0,    3./4]
])
g_ba_pinv_2

array([[0.33333333, 0.        ],
       [0.66666667, 0.        ],
       [0.        , 0.25      ],
       [0.        , 0.75      ]])

In [32]:
g_ba @ g_ba_pinv_2

array([[1., 1.]])

In [33]:
M_b = g_ba @ M_a @ g_ba_pinv
M_b

array([[1.125]])

In [35]:
np.linalg.eig(M_b)

(array([1.125]), array([[1.]]))

In [126]:
M_b_2 = g_ba @ M_a @ g_ba_pinv_2
M_b_2

array([[1.5, 0. ],
       [0. , 1.5]])

In [80]:
g_ba_pinv @ N_b

array([[6. ],
       [6. ],
       [4.5],
       [4.5]])

In [81]:
g_ba_pinv_2 @ N_b

array([[4.  ],
       [8.  ],
       [2.25],
       [6.75]])

In [82]:
lambda_, V = np.linalg.eig(M_a)

In [83]:
Lambda = np.diag(lambda_)

In [84]:
np.allclose(V @ Lambda @ np.linalg.inv(V), M_a)

True

In [85]:
Lambda

array([[1.5, 0. , 0. , 0. ],
       [0. , 0.5, 0. , 0. ],
       [0. , 0. , 1.5, 0. ],
       [0. , 0. , 0. , 0.5]])

In [86]:
g_ba @ V

array([[1.41421356e+00, 2.22044605e-16, 0.00000000e+00, 0.00000000e+00],
       [0.00000000e+00, 0.00000000e+00, 1.41421356e+00, 2.22044605e-16]])

In [87]:
np.linalg.inv(V) @ g_ba_pinv

array([[7.07106781e-01, 0.00000000e+00],
       [1.99051133e-16, 0.00000000e+00],
       [0.00000000e+00, 7.07106781e-01],
       [0.00000000e+00, 8.80288308e-17]])

In [52]:
M_b

array([[1.5, 0. ],
       [0. , 1.5]])

In [88]:
np.linalg.eig(M_b)

(array([1.5, 1.5]),
 array([[1., 0.],
        [0., 1.]]))

In [89]:
g_ba_pinv @ g_ba

array([[0.5, 0.5, 0. , 0. ],
       [0.5, 0.5, 0. , 0. ],
       [0. , 0. , 0.5, 0.5],
       [0. , 0. , 0.5, 0.5]])

In [90]:
g_ba_2 = np.array([
 [1, 1, 1, 0],
 [0, 0, 0, 1],
], dtype=float)
g_ba_2

array([[1., 1., 1., 0.],
       [0., 0., 0., 1.]])

In [91]:
g_ba_2_pinv = np.linalg.pinv(g_ba_2)
g_ba_2_pinv

array([[0.33333333, 0.        ],
       [0.33333333, 0.        ],
       [0.33333333, 0.        ],
       [0.        , 1.        ]])

In [92]:
M_b_2 = g_ba_2 @ M_a @ g_ba_2_pinv
M_b_2

array([[1.33333333, 0.5       ],
       [0.16666667, 1.        ]])

In [93]:
g_ba_2_pinv_2 = np.array([
       [0.2, 0.        ],
       [0.3, 0.        ],
       [0.5, 0.        ],
       [0. , 1.        ]
])

In [94]:
M_b_2_2 = g_ba_2 @ M_a @ g_ba_2_pinv
M_b_2_2

array([[1.33333333, 0.5       ],
       [0.16666667, 1.        ]])