In [592]:
import numpy as np

In [593]:
M_a = np.ones((5, 5)) * 0.1 + np.diag([1, 4, 9, 4, 1])
M_a

array([[1.1, 0.1, 0.1, 0.1, 0.1],
       [0.1, 4.1, 0.1, 0.1, 0.1],
       [0.1, 0.1, 9.1, 0.1, 0.1],
       [0.1, 0.1, 0.1, 4.1, 0.1],
       [0.1, 0.1, 0.1, 0.1, 1.1]])

In [624]:
g_ba = 2 * np.array([
    [1., 1, 1, 0, 0],
    #[0, 1, 0, 1, 0],
    [0, 0, 0, 1, 1]
])

In [595]:
g_ab_pinv = np.linalg.pinv(g_ba)
g_ab_pinv

array([[0.33333333, 0.        ],
       [0.33333333, 0.        ],
       [0.33333333, 0.        ],
       [0.        , 0.5       ],
       [0.        , 0.5       ]])

In [596]:
Lambda_col_a, V_a = np.linalg.eig(M_a)

In [597]:
Lambda_a = np.diag(Lambda_col_a)
Lambda_a, V_a

(array([[9.10681865, 0.        , 0.        , 0.        , 0.        ],
        [0.        , 1.        , 0.        , 0.        , 0.        ],
        [0.        , 0.        , 1.18453057, 0.        , 0.        ],
        [0.        , 0.        , 0.        , 4.20865078, 0.        ],
        [0.        , 0.        , 0.        , 0.        , 4.        ]]),
 array([[ 1.31683508e-02,  7.07106781e-01, -7.05494997e-01,
          4.58628808e-02, -2.95935493e-16],
        [ 2.09040970e-02,  4.20002662e-17,  4.62393212e-02,
          7.05283591e-01, -7.07106781e-01],
        [ 9.99389427e-01, -5.89911047e-17,  1.66573993e-02,
         -3.07132628e-02,  2.22849450e-16],
        [ 2.09040970e-02, -2.11269419e-16,  4.62393212e-02,
          7.05283591e-01,  7.07106781e-01],
        [ 1.31683508e-02, -7.07106781e-01, -7.05494997e-01,
          4.58628808e-02, -6.00452084e-16]]))

In [598]:
V_a @ Lambda_a @ np.linalg.inv(V_a)

array([[1.1, 0.1, 0.1, 0.1, 0.1],
       [0.1, 4.1, 0.1, 0.1, 0.1],
       [0.1, 0.1, 9.1, 0.1, 0.1],
       [0.1, 0.1, 0.1, 4.1, 0.1],
       [0.1, 0.1, 0.1, 0.1, 1.1]])

In [599]:
n_b, n_a = g_ba.shape

idx = Lambda_col_a.argsort()[-n_b:][::-1]
Lambda_col_b = Lambda_col_a[idx]  # top n_b eigenvalues
V_b = g_ba @ V_a[:,idx]           # corresponding eigenvectors

Lambda_b = np.diag(Lambda_col_b)
Lambda_b, V_b

(array([[9.10681865, 0.        ],
        [0.        , 4.20865078]]),
 array([[1.03346187, 0.72043321],
        [0.03407245, 0.75114647]]))

In [600]:
top_eigenvectors = V_a[:, idx]
X = np.linalg.inv(g_ba @ top_eigenvectors)
print(f'X = {X}')
g_ab_eig = top_eigenvectors @ X
#g_ab_eig = top_eigenvectors / (g_ba @ top_eigenvectors)
g_ab_eig

X = [[ 0.99921801 -0.95836147]
 [-0.04532512  1.37477011]]


array([[ 0.01107931,  0.05043088],
       [-0.01107931,  0.94956912],
       [ 1.        , -1.        ],
       [-0.01107931,  0.94956912],
       [ 0.01107931,  0.05043088]])

In [601]:
top_eigenvector = top_eigenvectors[:, 0]
top_eigenvector

array([0.01316835, 0.0209041 , 0.99938943, 0.0209041 , 0.01316835])

In [625]:
g_ab_top_eig = np.diag(top_eigenvector) @ g_ba.T @ np.linalg.inv(np.diag(g_ba @ top_eigenvector))
g_ab_top_eig

array([[0.01274198, 0.        ],
       [0.02022726, 0.        ],
       [0.96703076, 0.        ],
       [0.        , 0.61351908],
       [0.        , 0.38648092]])

In [626]:
g_ba @ g_ab_top_eig

array([[2., 0.],
       [0., 2.]])

In [604]:
top_eigenvector[:3] / sum(top_eigenvector[:3]),  top_eigenvector[3:] / sum(top_eigenvector[3:])

(array([0.01274198, 0.02022726, 0.96703076]), array([0.61351908, 0.38648092]))

In [605]:
g_ba @ top_eigenvector

array([1.03346187, 0.03407245])

In [606]:
M_b = V_b @ Lambda_b @ np.linalg.inv(V_b)
M_b, np.linalg.eig(M_b)

(array([[ 9.26676206, -4.85129263],
        [ 0.16676206,  4.04870737]]),
 (array([9.10681865, 4.20865078]),
  array([[0.99945696, 0.69219805],
         [0.03295133, 0.7217076 ]])))

In [607]:
M_b_pinv = g_ba @ M_a @ g_ab_pinv
M_b_pinv, np.linalg.eig(M_b_pinv)

(array([[4.96666667, 0.3       ],
        [0.2       , 2.7       ]]),
 (array([4.99283514, 2.67383152]),
  array([[ 0.99621719, -0.12973656],
         [ 0.08689828,  0.9915485 ]])))

In [608]:
M_b_top_eig = g_ba @ M_a @ g_ab_top_eig
M_b_top_eig, np.linalg.eig(M_b_top_eig)

(array([[9.09692788, 0.3       ],
        [0.2       , 3.04055725]]),
 (array([9.10681865, 3.03066648]),
  array([[ 0.99945696, -0.04939349],
         [ 0.03295133,  0.9987794 ]])))

In [609]:
M_b_eig = g_ba @ M_a @ g_ab_eig
M_b_eig, np.linalg.eig(M_b_eig)

(array([[ 9.26676206, -4.85129263],
        [ 0.16676206,  4.04870737]]),
 (array([9.10681865, 4.20865078]),
  array([[0.99945696, 0.69219805],
         [0.03295133, 0.7217076 ]])))

In [610]:
np.linalg.eig(M_a)

(array([9.10681865, 1.        , 1.18453057, 4.20865078, 4.        ]),
 array([[ 1.31683508e-02,  7.07106781e-01, -7.05494997e-01,
          4.58628808e-02, -2.95935493e-16],
        [ 2.09040970e-02,  4.20002662e-17,  4.62393212e-02,
          7.05283591e-01, -7.07106781e-01],
        [ 9.99389427e-01, -5.89911047e-17,  1.66573993e-02,
         -3.07132628e-02,  2.22849450e-16],
        [ 2.09040970e-02, -2.11269419e-16,  4.62393212e-02,
          7.05283591e-01,  7.07106781e-01],
        [ 1.31683508e-02, -7.07106781e-01, -7.05494997e-01,
          4.58628808e-02, -6.00452084e-16]]))

In [611]:
# N_a_0 = np.array([[1., 1., 1., 1., 1.]]).T
N_a_0 = np.array([[1., 0., 0., 0., 0.]]).T

In [612]:
T = 10

In [613]:
N_a = [np.linalg.matrix_power(M_a, t) @ N_a_0 for t in range(T)]
N_a

[array([[1.],
        [0.],
        [0.],
        [0.],
        [0.]]),
 array([[1.1],
        [0.1],
        [0.1],
        [0.1],
        [0.1]]),
 array([[1.25],
        [0.55],
        [1.05],
        [0.55],
        [0.25]]),
 array([[1.615],
        [2.565],
        [9.815],
        [2.565],
        [0.615]]),
 array([[ 3.3325],
        [11.9775],
        [90.0525],
        [11.9775],
        [ 2.3325]]),
 array([[ 15.29975],
        [ 59.87725],
        [822.43975],
        [ 59.87725],
        [ 14.29975]]),
 array([[ 112.479125],
        [ 336.688375],
        [7499.137125],
        [ 336.688375],
        [ 111.479125]]),
 array([[  952.1263375],
        [ 2186.4007125],
        [68331.8813375],
        [ 2186.4007125],
        [  951.1263375]]),
 array([[  8412.91988125],
        [ 16206.39639375],
        [622447.72558125],
        [ 16206.39639375],
        [  8411.91988125]]),
 array([[  75581.45569438],
        [ 131994.12138813],
        [5669198.06604438],
        [ 131

In [614]:
N_b = [g_ba @ N_a_i for N_a_i in N_a]
N_b

[array([[1.],
        [0.]]),
 array([[1.3],
        [0.2]]),
 array([[2.85],
        [0.8 ]]),
 array([[13.995],
        [ 3.18 ]]),
 array([[105.3625],
        [ 14.31  ]]),
 array([[897.61675],
        [ 74.177  ]]),
 array([[7948.304625],
        [ 448.1675  ]]),
 array([[71470.4083875],
        [ 3137.52705  ]]),
 array([[647067.04185625],
        [ 24618.316275  ]]),
 array([[5876773.64312688],
        [ 207574.5770825 ]])]

In [615]:
N_b_hat = [np.linalg.matrix_power(M_b, t) @ N_b[0] for t in range(T)]
N_b_hat

[array([[1.],
        [0.]]),
 array([[9.26676206],
        [0.16676206]]),
 array([[85.06386754],
        [ 2.22051513]]),
 array([[777.49425187],
        [ 23.17564189]]),
 array([[7092.42241551],
        [ 223.48793633]]),
 array([[64639.58558541],
        [ 2087.58423759]]),
 array([[588872.17734402],
        [ 19231.4482313 ]]),
 array([[5363640.96898176],
        [ 176064.04440969]]),
 array([[48849446.44150172],
        [ 1607283.6190139 ]]),
 array([[4.44878794e+08],
        [1.46536554e+07]])]

In [616]:
N_b_hat_pinv = [np.linalg.matrix_power(M_b_pinv, t) @ N_b[0] for t in range(T)]
N_b_hat_pinv

[array([[1.],
        [0.]]),
 array([[4.96666667],
        [0.2       ]]),
 array([[24.72777778],
        [ 1.53333333]]),
 array([[123.27462963],
        [  9.08555556]]),
 array([[614.98966049],
        [ 49.18592593]]),
 array([[3069.2044249],
        [ 255.7999321]]),
 array([[15320.45528995],
        [ 1304.50070165]]),
 array([[76482.94481726],
        [ 6586.24295243]]),
 array([[381841.1654781 ],
        [ 33079.44493503]]),
 array([[1906401.62202173],
        [ 165682.73442019]])]

In [617]:
N_b_hat_top_eig = [np.linalg.matrix_power(M_b_top_eig, t) @ N_b[0] for t in range(T)]
N_b_hat_top_eig

[array([[1.],
        [0.]]),
 array([[9.09692788],
        [0.2       ]]),
 array([[82.81409689],
        [ 2.42749703]]),
 array([[754.08211619],
        [ 23.94376307]]),
 array([[6867.01375718],
        [ 223.61880565]]),
 array([[62535.81455708],
        [ 2053.32853248]]),
 array([[569499.79364219],
        [ 18750.42587006]]),
 array([[5186323.67947061],
        [ 170911.70207189]]),
 array([[47230885.99668318],
        [ 1556931.55095434]]),
 array([[4.30123043e+08],
        [1.41801167e+07]])]

In [618]:
N_b_hat_eig = [np.linalg.matrix_power(M_b_eig, t) @ N_b[0] for t in range(T)]
N_b_hat_eig

[array([[1.],
        [0.]]),
 array([[9.26676206],
        [0.16676206]]),
 array([[85.06386754],
        [ 2.22051513]]),
 array([[777.49425187],
        [ 23.17564189]]),
 array([[7092.42241551],
        [ 223.48793633]]),
 array([[64639.58558541],
        [ 2087.58423759]]),
 array([[588872.17734402],
        [ 19231.4482313 ]]),
 array([[5363640.96898177],
        [ 176064.04440969]]),
 array([[48849446.4415018 ],
        [ 1607283.61901388]]),
 array([[4.44878794e+08],
        [1.46536554e+07]])]

In [619]:
'%E' % np.linalg.norm((N_b_hat[-1] - N_b[-1]))

'4.392396E+08'

In [620]:
'%E' % np.linalg.norm((N_b_hat_eig[-1] - N_b[-1]))

'4.392396E+08'

In [621]:
'%E' % np.linalg.norm((N_b_hat_top_eig[-1] - N_b[-1]))

'4.244763E+08'

In [622]:
'%E' % np.linalg.norm((N_b_hat_pinv[-1] - N_b[-1]))

'3.970593E+06'

In [ ]:
def evolve(M, N_0, num_steps=10):
    return [np.linalg.matrix_power(M, t) @ N_0 for t in range(num_steps)]

def evaluate(M_a=None, M_b=None, g_ba=None, N_a_0=None, num_steps=10):
    N_b_0 = g_ba @ N_a_0
    
    N_a = evolve(M_a, N_a_0, num_steps=num_steps)
    N_b = [g_ba @ N_a_t for N_a_t in N_a]
    N_b_hat = evolve(M_b, N_b_0, num_steps=num_steps)

    return {
        'N_a': N_a,
        'N_b': N_b,
        'N_b_hat': N_b_hat
    }